# Generated by Django 5.2.6 on 2025-09-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время платежа')),
                ('hide_amount', models.BooleanField(default=False, verbose_name='Скрыть сумму в ленте')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collects.collect', verbose_name='Сбор')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_datetime'],
            },
        ),
    ]
