# Generated by Django 5.2.6 on 2025-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название сбора')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('charity', 'Благотворительность'), ('medicine', 'Медицина'), ('education', 'Образование'), ('other', 'Другое')], max_length=20, verbose_name='Повод')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собранная сумма')),
                ('donators_count', models.PositiveIntegerField(default=0, verbose_name='Количество донатеров')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collect_covers/', verbose_name='Обложка сбора')),
            ],
            options={
                'verbose_name': 'Денежный сбор',
                'verbose_name_plural': 'Денежные сборы',
                'ordering': ['-created_at'],
            },
        ),
    ]
