# Generated by Django 5.2.6 on 2025-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Сбор завершен'),
        ),
    ]
