# Generated by Django 5.2.6 on 2025-09-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_collect_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='donators_count',
        ),
    ]
